### ISSUE TITLE
'can only test a child process'

### ISSUE THREAD

**Issue by DonMuv** [QVPR/Patch-NetVLAD#34]
Hi,
I encountered this error assert self._parent_pid == os.getpid(), 'can only test a child process' when I run train.py with the MSLS dataset

**Comment by Tobias-Fischer** [comment]
Could you please provide the full stack trace?

**Comment by DonMuv** [comment]
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>6 [00:00<?, ?it/s]
Traceback (most recent call last):
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
>> Searching for hard negatives...
Allocated: 170.45 MB                                                                                       
Cached:    4.72 GB                                                                                         
                                                                                                           Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>6 [00:32<?, ?it/s]
Traceback (most recent call last):                                                 | 0/123 [00:00<?, ?it/s]
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f4faf115ca0>
Traceback (most recent call last):
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/home/donmuv/anaconda3/envs/NetVlad/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'

**Comment by whnwwwhhhnnn** [comment]
May I ask how you resolved this issue？

**Comment by whu-lyh** [comment]
@Tobias-Fischer , @DonMuv , @whnwwwhhhnnn . I also met this error when I set the num_worker > 0, the training is stuck, and this error occurs:
```
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f81c5877c20>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f81c5877c20>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
```
The program succeeds when the num_works==0, however, the training process is slow, and the GPU usage rate is also low.
Any ideas to solve this error?

**Comment by whnwwwhhhnnn** [comment]
I set (persistent_workers=True) in (train_loader, val_loader) respectively, and the problem was solved.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QVPR/Patch-NetVLAD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月6日(星期天) 上午9:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [QVPR/Patch-NetVLAD] 'can only test a child process' (#34)





 
@Tobias-Fischer , @DonMuv , @whnwwwhhhnnn . I also met this error when I set the num_worker &gt; 0, the training is stuck, and this error occurs:
 Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f81c5877c20&gt; Traceback (most recent call last):   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__     self._shutdown_workers()   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers     if w.is_alive():   File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive     assert self._parent_pid == os.getpid(), 'can only test a child process' AssertionError: can only test a child process Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f81c5877c20&gt; Traceback (most recent call last):   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__     self._shutdown_workers()   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers     if w.is_alive():   File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 151, in is_alive     assert self._parent_pid == os.getpid(), 'can only test a child process'  
The program succeeds when the num_works==0, however, the training process is slow, and the GPU usage rate is also low.
 Any ideas to solve this error?

**Comment by whu-lyh** [comment]
Well, thanks!

**Comment by Tobias-Fischer** [comment]
Hi @whu-lyh @whnwwwhhhnnn - could you please open a pull request so we can fix this here? I am not sure which exact `DataLoader` you are referring to.
